### PR TITLE
Updating gRPC version in gradle build

### PR DESCRIPTION
**Pull request by dj144**
Updating gRPC version in gradle build for Apple Silicon

### CODE REVIEW

**Review by PellePedro — APPROVED** [review]
LGTM

**Comment by kslee** [comment]
will this be reflected on skyramp repo? otherwise we need to update there as well cc' @texmachina

**Comment by texmachina** [comment]
@kslee - We only replicate the skyramp dir over, so I think we are good?

**Comment by kslee** [comment]
ok

**Pull request merged**
